### ISSUE TITLE
Not working anymore

### ISSUE THREAD

**Issue by Heaven-Rajan** [Lynnette177/Overwatch-offsets-dumper#1]
It seems that following the latest Overwatch update, the dumper is only able to dump until the "decrypt visibility function." Beyond that point, no further data is extracted. Could you please verify this issue?

**Comment by Lynnette177** [comment]
guess what? some functions' pattern has changed, bcz blizzard has spotted this post, and they did obfusecate it.
If you ever looked through my code, you will find there is a button for you, to skip this scan if it get stuck. And obviously you didnt ever read my code, neither can you reverse Overwatch on your own to get new patterns.

**Comment by Heaven-Rajan** [comment]
If I could reverse it I wouldnt use your program like wtf is that statement LMFAO, are you mad or something?
Maybe stay a bit profesionell a dont get mad when Im legit just asking for help hahahah

**Comment by Lynnette177** [comment]
It seems that you are much more mad than me bcz I poked your sore spot
&nbsp;


Mercy
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2024年3月14日(星期四) 晚上8:37
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [Lynnette177/Overwatch-offsets-dumper] Not working anymore (Issue #1)





 
If I could reverse it I wouldnt use your program like wtf is that statement LMFAO, are you mad or something?
 Maybe stay a bit profesionell a dont get mad when Im legit just asking for help hahahah
